version: "3.9"
services: 
  web:
    image: nginx:${TAGN}
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm

  fpm:
    build: ./php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./web:/usr/share/nginx/html
    environment:
      DB_HOST: db:3306
      DB_DATABASE: ${DB_DATA}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
    depends_on:
      - db

  db:
    image: mariadb:${TAGM}
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATA}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

